import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface WorkpaperData {
  org_name: string;
  generated_at: string;
  generated_by: string;
  frameworks: string[];
  audit_period_start: string | null;
  audit_period_end: string | null;
  scope_notes: string | null;
  sample_controls: {
    control_id: string;
    title: string;
    status: string;
    severity: string | null;
    test_notes: string | null;
    test_attributes: Record<string, string> | null;
    tested_at: string | null;
    approved_at: string | null;
    comments: { author_email: string | null; body: string; created_at: string }[];
  }[];
  exceptions: { control_id: string; title: string; status: string; severity: string | null }[];
  pbc: { title: string; status: string; created_at: string; provided_at: string | null; reviewed_at: string | null; control_id: string | null }[];
}

const NAVY = [15, 23, 42] as [number, number, number];
const GREY = [100, 100, 100] as [number, number, number];
const LINE = [220, 220, 220] as [number, number, number];

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString();
}

function header(doc: jsPDF, title: string, orgName: string) {
  doc.setFontSize(20);
  doc.setTextColor(...NAVY);
  doc.text("ShieldBase Workpaper", 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(...GREY);
  doc.text(`${orgName} • generated ${new Date().toLocaleString()}`, 14, 25);
  doc.setDrawColor(...LINE);
  doc.line(14, 29, 196, 29);
  doc.setFontSize(15);
  doc.setTextColor(...NAVY);
  doc.text(title, 14, 38);
}

function footer(doc: jsPDF, page: number, total: number, generatedBy: string) {
  doc.setFontSize(8);
  doc.setTextColor(...GREY);
  doc.text(`Generated by ${generatedBy} • For audit workpaper use • Page ${page} of ${total}`, 14, 290);
}

export function generateWorkpaperPdf(data: WorkpaperData): Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // ---------- Cover page ----------
  doc.setFontSize(28);
  doc.setTextColor(...NAVY);
  doc.text("Audit Workpaper", 14, 60);
  doc.setFontSize(14);
  doc.setTextColor(...GREY);
  doc.text(data.org_name, 14, 72);
  doc.setFontSize(10);
  doc.setTextColor(...GREY);
  doc.text(`Frameworks: ${data.frameworks.join(", ") || "—"}`, 14, 90);
  if (data.audit_period_start || data.audit_period_end) {
    doc.text(`Audit period: ${fmtDate(data.audit_period_start)} → ${fmtDate(data.audit_period_end)}`, 14, 97);
  }
  doc.text(`Generated by: ${data.generated_by}`, 14, 104);
  doc.text(`Generated at: ${data.generated_at}`, 14, 111);
  if (data.scope_notes) {
    doc.setFontSize(11);
    doc.setTextColor(...NAVY);
    doc.text("Scope notes", 14, 130);
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    const wrapped = doc.splitTextToSize(data.scope_notes, 180);
    doc.text(wrapped, 14, 137);
  }

  // ---------- Sample summary ----------
  doc.addPage();
  header(doc, "Sample tested", data.org_name);
  if (data.sample_controls.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text("No controls were marked as in-sample for this engagement.", 14, 50);
  } else {
    autoTable(doc, {
      startY: 45,
      head: [["Control", "Title", "Status", "Tested", "Signed off"]],
      body: data.sample_controls.map(c => [
        c.control_id,
        c.title.length > 50 ? c.title.slice(0, 47) + "…" : c.title,
        c.status.replace("_", " "),
        fmtDate(c.tested_at),
        fmtDate(c.approved_at),
      ]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: NAVY, textColor: 255, fontSize: 8 },
      columnStyles: { 1: { cellWidth: 75 } },
    });
  }

  // ---------- Per-control test detail ----------
  for (const c of data.sample_controls) {
    doc.addPage();
    header(doc, `${c.control_id} — ${c.title}`, data.org_name);
    let y = 48;
    doc.setFontSize(10);
    doc.setTextColor(...NAVY);
    doc.text("Status", 14, y);
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text(c.status.replace("_", " "), 50, y);
    y += 6;
    if (c.severity) {
      doc.setTextColor(...NAVY);
      doc.text("Severity", 14, y);
      doc.setTextColor(...GREY);
      doc.text(c.severity, 50, y);
      y += 6;
    }
    doc.setTextColor(...NAVY);
    doc.text("Tested", 14, y);
    doc.setTextColor(...GREY);
    doc.text(fmtDate(c.tested_at), 50, y);
    y += 6;
    doc.setTextColor(...NAVY);
    doc.text("Signed off", 14, y);
    doc.setTextColor(...GREY);
    doc.text(fmtDate(c.approved_at), 50, y);
    y += 10;

    if (c.test_attributes) {
      doc.setFontSize(11);
      doc.setTextColor(...NAVY);
      doc.text("Test attributes", 14, y);
      y += 4;
      autoTable(doc, {
        startY: y,
        head: [["Attribute", "Result"]],
        body: ["complete", "accurate", "authorized", "timely"].map(k =>
          [k.charAt(0).toUpperCase() + k.slice(1), c.test_attributes?.[k] ?? "—"]),
        styles: { fontSize: 9 },
        headStyles: { fillColor: NAVY, textColor: 255, fontSize: 9 },
      });
      // @ts-expect-error jspdf-autotable adds lastAutoTable
      y = (doc.lastAutoTable?.finalY ?? y) + 8;
    }

    if (c.test_notes) {
      doc.setFontSize(11);
      doc.setTextColor(...NAVY);
      doc.text("Test notes", 14, y);
      y += 5;
      doc.setFontSize(9);
      doc.setTextColor(...GREY);
      const wrapped = doc.splitTextToSize(c.test_notes, 180);
      doc.text(wrapped, 14, y);
      y += wrapped.length * 4 + 4;
    }

    if (c.comments.length > 0) {
      doc.setFontSize(11);
      doc.setTextColor(...NAVY);
      doc.text("Comments", 14, y);
      y += 5;
      for (const cm of c.comments) {
        if (y > 270) { doc.addPage(); header(doc, `${c.control_id} — Comments (cont.)`, data.org_name); y = 48; }
        doc.setFontSize(8);
        doc.setTextColor(...GREY);
        doc.text(`${cm.author_email ?? "?"} • ${fmtDate(cm.created_at)}`, 14, y);
        y += 4;
        doc.setFontSize(9);
        doc.setTextColor(...NAVY);
        const wrapped = doc.splitTextToSize(cm.body, 180);
        doc.text(wrapped, 14, y);
        y += wrapped.length * 4 + 3;
      }
    }
  }

  // ---------- Exceptions ----------
  doc.addPage();
  header(doc, "Exceptions", data.org_name);
  if (data.exceptions.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text("No exceptions recorded — all assessed controls passing.", 14, 50);
  } else {
    autoTable(doc, {
      startY: 45,
      head: [["Control", "Title", "Status", "Severity"]],
      body: data.exceptions.map(e => [
        e.control_id,
        e.title.length > 60 ? e.title.slice(0, 57) + "…" : e.title,
        e.status.replace("_", " "),
        e.severity ?? "—",
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: NAVY, textColor: 255 },
      columnStyles: { 1: { cellWidth: 90 } },
    });
  }

  // ---------- PBC log ----------
  doc.addPage();
  header(doc, "PBC log", data.org_name);
  if (data.pbc.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text("No PBC requests recorded.", 14, 50);
  } else {
    autoTable(doc, {
      startY: 45,
      head: [["Title", "Control", "Status", "Created", "Provided", "Reviewed"]],
      body: data.pbc.map(p => [
        p.title.length > 38 ? p.title.slice(0, 35) + "…" : p.title,
        p.control_id ?? "—",
        p.status,
        fmtDate(p.created_at),
        fmtDate(p.provided_at),
        fmtDate(p.reviewed_at),
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: NAVY, textColor: 255 },
    });
  }

  // ---------- Footer pagination ----------
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    footer(doc, i, total, data.generated_by);
  }

  return doc.output("blob");
}
