import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface WorkpaperData {
  org_name: string;
  generated_at: string;
  generated_by: string;
  frameworks: string[];
  audit_period_start: string | null;
  audit_period_end: string | null;
  scope_notes: string | null;
  sample_controls: {
    control_id: string;
    title: string;
    status: string;
    severity: string | null;
    test_notes: string | null;
    test_attributes: Record<string, string> | null;
    tested_at: string | null;
    approved_at: string | null;
    comments: { author_email: string | null; body: string; created_at: string }[];
  }[];
  exceptions: { control_id: string; title: string; status: string; severity: string | null }[];
  pbc: { title: string; status: string; created_at: string; provided_at: string | null; reviewed_at: string | null; control_id: string | null }[];
  findings?: {
    control_id: string | null;
    title: string;
    severity: string;
    disposition: string;
    status: string;
    management_response: string | null;
    remediation_owner_email: string | null;
    remediation_target_date: string | null;
    auditor_conclusion: string | null;
  }[];
  test_instances?: {
    control_id: string;
    period_start: string | null;
    period_end: string | null;
    tested_by_email: string | null;
    tested_at: string;
    test_procedure: string | null;
    sample_ids: string | null;
    conclusion: string | null;
  }[];
}

const NAVY = [15, 23, 42] as [number, number, number];
const GREY = [100, 100, 100] as [number, number, number];
const LINE = [220, 220, 220] as [number, number, number];

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString();
}

function header(doc: jsPDF, title: string, orgName: string) {
  doc.setFontSize(20);
  doc.setTextColor(...NAVY);
  doc.text("ShieldBase Workpaper", 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(...GREY);
  doc.text(`${orgName} • generated ${new Date().toLocaleString()}`, 14, 25);
  doc.setDrawColor(...LINE);
  doc.line(14, 29, 196, 29);
  doc.setFontSize(15);
  doc.setTextColor(...NAVY);
  doc.text(title, 14, 38);
}

function footer(doc: jsPDF, page: number, total: number, generatedBy: string) {
  doc.setFontSize(8);
  doc.setTextColor(...GREY);
  doc.text(`Generated by ${generatedBy} • For audit workpaper use • Page ${page} of ${total}`, 14, 290);
}

export function generateWorkpaperPdf(data: WorkpaperData): Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // ---------- Cover page ----------
  doc.setFontSize(28);
  doc.setTextColor(...NAVY);
  doc.text("Audit Workpaper", 14, 60);
  doc.setFontSize(14);
  doc.setTextColor(...GREY);
  doc.text(data.org_name, 14, 72);
  doc.setFontSize(10);
  doc.setTextColor(...GREY);
  doc.text(`Frameworks: ${data.frameworks.join(", ") || "—"}`, 14, 90);
  if (data.audit_period_start || data.audit_period_end) {
    doc.text(`Audit period: ${fmtDate(data.audit_period_start)} → ${fmtDate(data.audit_period_end)}`, 14, 97);
  }
  doc.text(`Generated by: ${data.generated_by}`, 14, 104);
  doc.text(`Generated at: ${data.generated_at}`, 14, 111);
  if (data.scope_notes) {
    doc.setFontSize(11);
    doc.setTextColor(...NAVY);
    doc.text("Scope notes", 14, 130);
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    const wrapped = doc.splitTextToSize(data.scope_notes, 180);
    doc.text(wrapped, 14, 137);
  }

  // ---------- Independent Service Auditor's Report (template) ----------
  doc.addPage();
  header(doc, "Independent Service Auditor's Report", data.org_name);
  {
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    const isar = [
      `To the management of ${data.org_name}:`,
      "",
      `We have examined ${data.org_name}'s accompanying description of its system and the suitability of the design and operating effectiveness of controls to meet the criteria for the ${data.frameworks.join(", ") || "SOC 2"} trust services criteria throughout the period ${fmtDate(data.audit_period_start)} to ${fmtDate(data.audit_period_end)}.`,
      "",
      "Management's responsibility: Management is responsible for preparing the description and assertion, providing the services covered, specifying the service commitments and system requirements, identifying risks that threaten the achievement of the service commitments and system requirements, designing and implementing effective controls, and evaluating their effectiveness throughout the period.",
      "",
      "Our responsibility: Our responsibility is to express an opinion on the description, and on the suitability of the design and operating effectiveness of the controls to achieve the related criteria stated in the description.",
      "",
      "Scope: Our examination was conducted in accordance with attestation standards established by the AICPA. Those standards require that we plan and perform our examination to obtain reasonable assurance about whether, in all material respects, the description is presented in accordance with the description criteria and the controls were suitably designed and operating effectively.",
      "",
      "[OPINION PARAGRAPH — to be populated from exceptions + conclusions]",
      "",
      "— This page is a generated template. Populate [bracketed] fields with firm-specific details before issuance.",
    ].join("\n");
    const wrapped = doc.splitTextToSize(isar, 180);
    doc.text(wrapped, 14, 48);
  }

  // ---------- Management Assertion (template) ----------
  doc.addPage();
  header(doc, "Management Assertion", data.org_name);
  {
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    const assertion = [
      `We, the management of ${data.org_name}, are responsible for:`,
      "• designing, implementing, and operating the controls to provide reasonable assurance that the service commitments and system requirements related to the trust services criteria are achieved;",
      "• selecting the trust services categories covered by this report;",
      "• identifying the risks that threaten the achievement of those service commitments and system requirements;",
      "• preparing the accompanying description of our system.",
      "",
      `We assert that the description fairly presents ${data.org_name}'s ${data.frameworks.join(", ") || "SOC 2"} system throughout the period ${fmtDate(data.audit_period_start)} to ${fmtDate(data.audit_period_end)} and that the controls stated in the description were suitably designed and operating effectively throughout that period.`,
      "",
      "Signature: _________________________________",
      "Name/Title: _______________________________",
      "Date: _____________________________________",
    ].join("\n");
    const wrapped = doc.splitTextToSize(assertion, 180);
    doc.text(wrapped, 14, 48);
  }

  // ---------- System Description (template) ----------
  doc.addPage();
  header(doc, "System Description", data.org_name);
  {
    doc.setFontSize(10);
    doc.setTextColor(...NAVY);
    doc.text("Services provided", 14, 48);
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    doc.text(data.scope_notes ? doc.splitTextToSize(data.scope_notes, 180) : "[describe the services in scope, user entities, sub-service organizations, and carve-out/inclusive choices]", 14, 54);

    doc.setFontSize(10);
    doc.setTextColor(...NAVY);
    doc.text("Frameworks covered", 14, 100);
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    doc.text(data.frameworks.join(", ") || "—", 14, 106);

    doc.setFontSize(10);
    doc.setTextColor(...NAVY);
    doc.text("Infrastructure, software, people, procedures, data", 14, 120);
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    doc.text(
      [
        "[Infrastructure: list cloud providers, datacenters, and network segments in scope.]",
        "[Software: list key applications, security tools, and monitoring platforms.]",
        "[People: describe roles (engineering, security, support) with access to in-scope systems.]",
        "[Procedures: reference the organization's key policies and standard operating procedures.]",
        "[Data: describe data types processed, classification, and retention.]",
      ].join("\n"),
      14, 126
    );
  }

  // ---------- Control matrix by TSC ----------
  doc.addPage();
  header(doc, "Control matrix by TSC category", data.org_name);
  {
    const byCat: Record<string, { total: number; compliant: number }> = {};
    for (const c of data.sample_controls) {
      const cat = c.control_id.split(".")[0] || "Other";
      const b = (byCat[cat] ||= { total: 0, compliant: 0 });
      b.total += 1;
      if (c.status === "compliant") b.compliant += 1;
    }
    const rows = Object.entries(byCat).map(([cat, b]) => [
      cat, String(b.total), String(b.compliant), String(b.total - b.compliant),
      `${b.total ? Math.round((b.compliant / b.total) * 100) : 0}%`,
    ]);
    if (rows.length === 0) {
      doc.setFontSize(10);
      doc.setTextColor(...GREY);
      doc.text("No in-sample controls to aggregate.", 14, 50);
    } else {
      autoTable(doc, {
        startY: 45,
        head: [["TSC category", "Total", "Compliant", "Not compliant", "Pass rate"]],
        body: rows,
        styles: { fontSize: 9 },
        headStyles: { fillColor: NAVY, textColor: 255 },
      });
    }
  }

  // ---------- Sample summary ----------
  doc.addPage();
  header(doc, "Sample tested", data.org_name);
  if (data.sample_controls.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text("No controls were marked as in-sample for this engagement.", 14, 50);
  } else {
    autoTable(doc, {
      startY: 45,
      head: [["Control", "Title", "Status", "Tested", "Signed off"]],
      body: data.sample_controls.map(c => [
        c.control_id,
        c.title.length > 50 ? c.title.slice(0, 47) + "…" : c.title,
        c.status.replace("_", " "),
        fmtDate(c.tested_at),
        fmtDate(c.approved_at),
      ]),
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: NAVY, textColor: 255, fontSize: 8 },
      columnStyles: { 1: { cellWidth: 75 } },
    });
  }

  // ---------- Per-control test detail ----------
  for (const c of data.sample_controls) {
    doc.addPage();
    header(doc, `${c.control_id} — ${c.title}`, data.org_name);
    let y = 48;
    doc.setFontSize(10);
    doc.setTextColor(...NAVY);
    doc.text("Status", 14, y);
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text(c.status.replace("_", " "), 50, y);
    y += 6;
    if (c.severity) {
      doc.setTextColor(...NAVY);
      doc.text("Severity", 14, y);
      doc.setTextColor(...GREY);
      doc.text(c.severity, 50, y);
      y += 6;
    }
    doc.setTextColor(...NAVY);
    doc.text("Tested", 14, y);
    doc.setTextColor(...GREY);
    doc.text(fmtDate(c.tested_at), 50, y);
    y += 6;
    doc.setTextColor(...NAVY);
    doc.text("Signed off", 14, y);
    doc.setTextColor(...GREY);
    doc.text(fmtDate(c.approved_at), 50, y);
    y += 10;

    if (c.test_attributes) {
      doc.setFontSize(11);
      doc.setTextColor(...NAVY);
      doc.text("Test attributes", 14, y);
      y += 4;
      autoTable(doc, {
        startY: y,
        head: [["Attribute", "Result"]],
        body: ["complete", "accurate", "authorized", "timely"].map(k =>
          [k.charAt(0).toUpperCase() + k.slice(1), c.test_attributes?.[k] ?? "—"]),
        styles: { fontSize: 9 },
        headStyles: { fillColor: NAVY, textColor: 255, fontSize: 9 },
      });
      // @ts-expect-error jspdf-autotable adds lastAutoTable
      y = (doc.lastAutoTable?.finalY ?? y) + 8;
    }

    if (c.test_notes) {
      doc.setFontSize(11);
      doc.setTextColor(...NAVY);
      doc.text("Test notes", 14, y);
      y += 5;
      doc.setFontSize(9);
      doc.setTextColor(...GREY);
      const wrapped = doc.splitTextToSize(c.test_notes, 180);
      doc.text(wrapped, 14, y);
      y += wrapped.length * 4 + 4;
    }

    if (c.comments.length > 0) {
      doc.setFontSize(11);
      doc.setTextColor(...NAVY);
      doc.text("Comments", 14, y);
      y += 5;
      for (const cm of c.comments) {
        if (y > 270) { doc.addPage(); header(doc, `${c.control_id} — Comments (cont.)`, data.org_name); y = 48; }
        doc.setFontSize(8);
        doc.setTextColor(...GREY);
        doc.text(`${cm.author_email ?? "?"} • ${fmtDate(cm.created_at)}`, 14, y);
        y += 4;
        doc.setFontSize(9);
        doc.setTextColor(...NAVY);
        const wrapped = doc.splitTextToSize(cm.body, 180);
        doc.text(wrapped, 14, y);
        y += wrapped.length * 4 + 3;
      }
    }
  }

  // ---------- Exceptions ----------
  doc.addPage();
  header(doc, "Exceptions", data.org_name);
  if (data.exceptions.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text("No exceptions recorded — all assessed controls passing.", 14, 50);
  } else {
    autoTable(doc, {
      startY: 45,
      head: [["Control", "Title", "Status", "Severity"]],
      body: data.exceptions.map(e => [
        e.control_id,
        e.title.length > 60 ? e.title.slice(0, 57) + "…" : e.title,
        e.status.replace("_", " "),
        e.severity ?? "—",
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: NAVY, textColor: 255 },
      columnStyles: { 1: { cellWidth: 90 } },
    });
  }

  // ---------- PBC log ----------
  doc.addPage();
  header(doc, "PBC log", data.org_name);
  if (data.pbc.length === 0) {
    doc.setFontSize(10);
    doc.setTextColor(...GREY);
    doc.text("No PBC requests recorded.", 14, 50);
  } else {
    autoTable(doc, {
      startY: 45,
      head: [["Title", "Control", "Status", "Created", "Provided", "Reviewed"]],
      body: data.pbc.map(p => [
        p.title.length > 38 ? p.title.slice(0, 35) + "…" : p.title,
        p.control_id ?? "—",
        p.status,
        fmtDate(p.created_at),
        fmtDate(p.provided_at),
        fmtDate(p.reviewed_at),
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: NAVY, textColor: 255 },
    });
  }

  // ---------- Findings & Exceptions Log ----------
  if ((data.findings ?? []).length > 0) {
    doc.addPage();
    header(doc, "Findings & Exceptions Log", data.org_name);
    autoTable(doc, {
      startY: 45,
      head: [["Control", "Title", "Severity", "Disposition", "Status", "Target"]],
      body: (data.findings ?? []).map(f => [
        f.control_id ?? "—",
        f.title.length > 40 ? f.title.slice(0, 37) + "…" : f.title,
        f.severity,
        f.disposition.replace(/_/g, " "),
        f.status,
        f.remediation_target_date ? fmtDate(f.remediation_target_date) : "—",
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: NAVY, textColor: 255 },
      columnStyles: { 1: { cellWidth: 65 } },
    });

    // Per-finding detail (one per page for clarity)
    for (const f of data.findings ?? []) {
      doc.addPage();
      header(doc, `Finding — ${f.control_id ?? "narrative"}`, data.org_name);
      let y = 48;
      doc.setFontSize(11);
      doc.setTextColor(...NAVY);
      doc.text(f.title, 14, y);
      y += 8;
      doc.setFontSize(9);
      doc.setTextColor(...GREY);
      doc.text(`Severity: ${f.severity} · Disposition: ${f.disposition.replace(/_/g, " ")} · Status: ${f.status}`, 14, y);
      y += 8;
      if (f.auditor_conclusion) {
        doc.setTextColor(...NAVY); doc.text("Auditor conclusion", 14, y); y += 5;
        doc.setTextColor(...GREY);
        const wrapped = doc.splitTextToSize(f.auditor_conclusion, 180);
        doc.text(wrapped, 14, y); y += wrapped.length * 5 + 3;
      }
      if (f.management_response) {
        doc.setTextColor(...NAVY); doc.text("Management response", 14, y); y += 5;
        doc.setTextColor(...GREY);
        const wrapped = doc.splitTextToSize(f.management_response, 180);
        doc.text(wrapped, 14, y); y += wrapped.length * 5 + 3;
      }
      if (f.remediation_owner_email || f.remediation_target_date) {
        doc.setTextColor(...NAVY); doc.text("Remediation", 14, y); y += 5;
        doc.setTextColor(...GREY);
        doc.text(`${f.remediation_owner_email ?? "—"} · target ${f.remediation_target_date ?? "—"}`, 14, y);
      }
    }
  }

  // ---------- Test iterations (Type II period coverage proof) ----------
  if ((data.test_instances ?? []).length > 0) {
    doc.addPage();
    header(doc, "Test iteration log", data.org_name);
    doc.setFontSize(9);
    doc.setTextColor(...GREY);
    doc.text("One row per test run. Required for Type II to demonstrate control operated throughout the period.", 14, 45);
    autoTable(doc, {
      startY: 52,
      head: [["Control", "Period", "Tester", "Date", "Procedure", "Conclusion"]],
      body: (data.test_instances ?? []).map(t => [
        t.control_id,
        t.period_start && t.period_end ? `${t.period_start} → ${t.period_end}` : (t.period_start ?? t.period_end ?? "—"),
        t.tested_by_email ?? "—",
        fmtDate(t.tested_at),
        t.test_procedure ?? "—",
        (t.conclusion ?? "").length > 60 ? (t.conclusion ?? "").slice(0, 57) + "…" : (t.conclusion ?? "—"),
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: NAVY, textColor: 255 },
      columnStyles: { 5: { cellWidth: 60 } },
    });
  }

  // ---------- Footer pagination ----------
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    footer(doc, i, total, data.generated_by);
  }

  return doc.output("blob");
}
